# Generated by Django 5.2.1 on 2025-05-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0003_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
