# Generated by Django 5.2.1 on 2025-05-22 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0004_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
